### ISSUE TITLE
Licensing change to CC BY-SA 4.0

### ISSUE THREAD

**Issue by gibbed** [xenia-project/xenia-project.github.io#1]
The Xenia website was never explicitly licensed.

I'd like to ask everyone that has commits in the repository (formerly the `gh-pages` branch on the `xenia` repo) to affirm approval with licensing the website under [CC BY-SA 4.0](https://github.com/xenia-project/xenia/blob/master/assets/icon/LICENSE), as Xenia's logo/icon is.

*Except where this isn't possible/content that isn't ours, such as game screenshots, which will be appropriately marked as such.*

Contributors needed to approve this change:
- [x] @benvanik
- [x] @gibbed
- [x] @DrChat
- [x] @Triang3l
- [x] @Margen67
- [x] @Razzile
- [x] @illusion0001
- [x] ~~@drillsar~~ **Commits removed.**
- [x] ~~@tmccaff~~ **Commits removed.**
- [x] @RobertTheProfessional

If there isn't a response in sufficient time by anyone in this list or they voice their disapproval, will move forward by removing or otherwise replacing the content that person contributed.

**Comment by DrChat** [comment]
Approved!

**Comment by gibbed** [comment]
Approved (just for clarity/not in the issue itself)

**Comment by Triang3l** [comment]
Approved :catPat:

**Comment by illusionyy** [comment]
Approved 😺😺😺

**Comment by Margen67** [comment]
I approve.

**Comment by Razzile** [comment]
I approve

**Comment by benvanik** [comment]
I approve!

**Comment by gibbed** [comment]
History has been rewritten to remove commits by drillsar, tmccaff since they have not responded in an adequate amount of time.
